version: 2

# executors:
#   docker-publisher:
#     environment:
#       IMAGE_TAG: dockervoyager/oc-lettings:latest
#     docker:
#       - image: docker:stable

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

  test:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Test Preparation
            command: |
              . venv/bin/activate
              sudo apt-get update
              sudo apt-get install chromium -y
              sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
              sudo dpkg -i google-chrome-stable_current_amd64.deb
              sudo apt-get -fy install
              mkdir test-results
          name: Test Launch
            command: |
              pytest --junitxml=test-results/junit.xml
              python manage.py test

      - store_artifacts:
          path: test-reports/
          destination: python_app
      - store_test_results:
          path: test-results

  coverage:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name : Coverage 
          command: |
            python -m pip install -r requirements.txt
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov
    
  push:


workflows:
  version: 2
  build_test_and_coverage:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test