# Generated by Django 3.0 on 2022-06-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220610_0947'),
    ]

    operations = [

        
        migrations.SeparateDatabaseAndState(
                state_operations=[
                    migrations.DeleteModel(
                        name='Letting',
                    ),
                ],

                database_operations=[
                    migrations.AlterModelTable(
                    name='Letting',
                    table='lettings_letting',
                    ),

                    ],)
    ]
